# Zram optimization for ThinkPad X390
# Насърчава RAM да остава в self-refresh mode по-дълго
SATA_LINKPWR_ON_BAT=med_power_with_dipm
SATA_LINKPWR_ON_AC=med_power_with_dipm

# Намалява агресивността на memory compaction
KERNEL_PARAMETERS="transparent_hugepage=always"
